### PR TITLE
Compatibility with apecs-0.5.1.0 + small fixes

### PR DESCRIPTION
**Pull request by gdeest**
This commit:
- Bumps apecs to 0.5.1.0 in `stack.yaml`.
- Fixes ensuing compiler errors.
- Bumps Stackage LTS to 10.10 (GHC 8.2.2).
- Fixes linker errors on NixOS.

See #5 for some context.

### CODE REVIEW

**Comment by gdeest** [comment]
Hmmm, I'll look into the CI failures.

**Comment by jonascarpay** [comment]
Thank you for looking into this. I am having issues on nixos as well, but I'm fairly new to Nix and was planning to just wait until 0.5.1.0 made it into nixpkgs.

**Comment by gdeest** [comment]
My working hypothesis is that `stack --nix` does not work well with `inline-c` < 0.6. I am not entirely sure though, but bumping to a newer LTS was what solved the linker errors for me.

**Comment by gdeest** [comment]
Maybe GHC 8.0.X-related, actually, which is fairly old by Haskell standards... I'll try to fix it if I can, but would you be open to requiring GHC >= 8.2.0 ? At the very least, I think CI should exercise the build for newer versions.

Fixing the build for GHC HEAD and stackage nightly will require further changes to the codebase (beyond specifying a Gloss version in extra-deps). For instance, there is the `Semigroup m => Monoid m` change in GHC 8.4 which is currently not handled (can be done with `CPP`).

**Comment by gdeest** [comment]
PTAL.

As it turns out, `inline-c` behaves differently for GHC prior to GHC 8.2: it outputs files in the source directories, which must be explicitly included in the Cabal file.

I worked around the issue by adding a custom `Setup.hs`, which conditionally includes said files based on compiler version. Now all tests are green, except for non-stack GHC 8.0.2 build which performs an additional `cabal check`. This one fails with warnings related to `-O2` and missing `license` file -- I think you're in a better position to decide what to do with them.

**Comment by jonascarpay** [comment]
Dropping support for GHC <8.2 is definitely acceptable if that's what it takes. I hope to eventually move away from inline-c and just use the FFI for the sake of portability, but it's not a priority.
The issue with GHC HEAD is also present in apecs, I expect it to go away when I fix it upstream. I fixed the Semigroup issue in apecs [like this](https://github.com/jonascarpay/apecs/blob/master/src/Apecs/Util.hs#L37), which seems to be portable.

**Comment by gdeest-da** [comment]
It builds fine with GHC 8.0 and GHC 8.2 now, thanks to a `Setup.hs` hack.

I am curious: what are you concerns regarding `inline-c` and portability ? It seems fairly portable to me.

**Comment by gdeest** [comment]
It builds fine with GHC 8.0 and GHC 8.2 now, thanks to a `Setup.hs` hack.

I am curious: what are you concerns regarding `inline-c` and portability ? It seems fairly portable to me.

**Comment by jonascarpay** [comment]
Thank you very much for your work! I'll add the license file and push to hackage.
Inline-c was useful while hacking but now that the C parts have mostly been worked out, I don't think it has any real added benefit over just using the FFI. I'm happy with the Setup.hs solution but if the FFI is simpler, I'd rather eventually just avoid the dependency on it and template-haskell entirely. OTOH, I have never used the FFI so it might be just as much of a pain...

**Pull request merged**
